const ProjectData = [
  {
    title: 'ONBOOKING',
    description: 'OnBooking is a comprehensive accommodation booking platform like Airbnb designed to provide users with a seamless experience in finding and booking their ideal accommodations.',
    imageUrl: './assets/onbooking.AVIF',
    tech: 'Rails, JavaScript, TailwindCSS',
    seelivelink: 'https://onbooking-1ceff53c6093.herokuapp.com/',
    seesourcelink: 'https://github.com/binodbhusal/onbooking',
  },
  {
    title: 'AMAZON CLONE',
    description: 'The Amazon Clone is a comprehensive E-commerce web application inspired by the renowned Amazon online marketplace.',
    imageUrl: './assets/amazon_clone.AVIF',
    tech: 'React, Firebase, Redux, TailwindCSS',
    seelivelink: 'https://clone-1b966.web.app/',
    seesourcelink: 'https://github.com/binodbhusal/amazon-clone',
  },
  {
    title: 'MOTORHUB',
    description: 'Web application designed to provide users with the ability to reserve, view, and manage motors such as cars and bikes reservation for purchases. ',
    imageUrl: './assets/motofinal.AVIF',
    tech: 'Rails, React, Redux',
    seelivelink: 'https://motorhub.netlify.app/',
    seesourcelink: 'https://github.com/binodbhusal/motorhub_backend.git',
  },
  {
    title: 'iTALK',
    description: 'This project utilizes cutting-edge technologies including Next.js and TypeScript to emulate the functionality of Zoom, a popular video conferencing platform.',
    imageUrl: './assets/italk1.AVIF',
    tech: 'Next.js, TypeScript, React, Tailwind CSS',
    seelivelink: 'https://italk-sand.vercel.app/',
    seesourcelink: 'https://github.com/binodbhusal/italk',
  },
  {
    title: 'CRYPTOFY',
    description: 'Web application that provides users with a comprehensive view of various cryptocurrency exchanges and their trading data.',
    imageUrl: './assets/cryptofy.AVIF',
    tech: 'React, Redux, JavaScript',
    seelivelink: 'https://cryptofy.onrender.com/',
    seesourcelink: 'https://github.com/binodbhusal/cryptofy',
  },
  {
    title: 'BUDGET APP',
    description: 'Web-based personal finance management application designed to help users manage their finances effectively.It offers a user-friendly interface to track income, expenses, and budget goals.',
    imageUrl: './assets/budgetappfinal.AVIF',
    tech: 'Rails, HTML/CSS',
    seelivelink: 'https://mybudgetapp-qm8w.onrender.com/',
    seesourcelink: 'https://github.com/binodbhusal/BudgetApp',
  },

  {
    title: 'BLOG APP',
    description: 'BlogApp allows users to create personalized profiles where they can showcae their information, including a profile photo and breif bio. Users can create, edit and delete their own blog posts.',
    imageUrl: './assets/BLOGAPP.AVIF',
    tech: 'Rails, HTML/CSS',
    seelivelink: 'https://blogapp-5efk.onrender.com',
    seesourcelink: 'https://github.com/binodbhusal/BlogApp',
  },
];
export default ProjectData;
